/**
 * Multi-Language AI Subtitle Translator & Dubbing Engine for EditFlow AI
 * Translates transcript & subtitles into 12 global languages with context-aware
 * translation tables and matched localized TTS language tags.
 */

export interface SupportedLanguage {
  code: string;
  name: string;
  flag: string;
  nativeName: string;
  voiceLocale: string;
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español', voiceLocale: 'es-ES' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français', voiceLocale: 'fr-FR' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch', voiceLocale: 'de-DE' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी', voiceLocale: 'hi-IN' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', nativeName: '日本語', voiceLocale: 'ja-JP' },
  { code: 'pt', name: 'Portuguese', flag: '🇧🇷', nativeName: 'Português', voiceLocale: 'pt-BR' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano', voiceLocale: 'it-IT' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية', voiceLocale: 'ar-SA' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', nativeName: '한국어', voiceLocale: 'ko-KR' },
  { code: 'zh', name: 'Chinese (Simplified)', flag: '🇨🇳', nativeName: '简体中文', voiceLocale: 'zh-CN' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', nativeName: 'Русский', voiceLocale: 'ru-RU' },
  { code: 'nl', name: 'Dutch', flag: '🇳🇱', nativeName: 'Nederlands', voiceLocale: 'nl-NL' },
];

/**
 * Contextual translation dictionary for high-frequency video editing and viral content terms
 */
const DICTIONARY: Record<string, Record<string, string>> = {
  es: {
    transform: 'transforma',
    your: 'tu',
    content: 'contenido',
    into: 'en',
    viral: 'viral',
    high: 'alto',
    engagement: 'compromiso',
    videos: 'videos',
    with: 'con',
    ai: 'IA',
    stop: 'para',
    scrolling: 'de deslizar',
    this: 'esto',
    changes: 'cambia',
    everything: 'todo',
    the: 'el',
    secret: 'secreto',
    growth: 'crecimiento',
    money: 'dinero',
    how: 'cómo',
    to: 'para',
    automate: 'automatizar',
    editing: 'edición',
    listen: 'escucha',
    carefully: 'atentamente',
  },
  fr: {
    transform: 'transformez',
    your: 'votre',
    content: 'contenu',
    into: 'en',
    viral: 'virales',
    high: 'fort',
    engagement: 'engagement',
    videos: 'vidéos',
    with: 'avec',
    ai: 'IA',
    stop: 'arrêtez',
    scrolling: 'de scroller',
    this: 'ceci',
    changes: 'change',
    everything: 'tout',
    the: 'le',
    secret: 'secret',
    growth: 'croissance',
    money: 'argent',
    how: 'comment',
    to: 'pour',
    automate: 'automatiser',
    editing: 'montage',
    listen: 'écoutez',
    carefully: 'attentivement',
  },
  de: {
    transform: 'verwandeln',
    your: 'deinen',
    content: 'Inhalt',
    into: 'in',
    viral: 'virale',
    high: 'hohe',
    engagement: 'Interaktion',
    videos: 'Videos',
    with: 'mit',
    ai: 'KI',
    stop: 'stoppen',
    scrolling: 'Sie das Scrollen',
    this: 'dies',
    changes: 'verändert',
    everything: 'alles',
    the: 'das',
    secret: 'Geheimnis',
    growth: 'Wachstum',
    money: 'Geld',
    how: 'wie',
    to: 'man',
    automate: 'automatisiert',
    editing: 'Videobearbeitung',
    listen: 'hören',
    carefully: 'Sie genau hin',
  },
  hi: {
    transform: 'बदलें',
    your: 'अपनी',
    content: 'सामग्री को',
    into: 'में',
    viral: 'वायरल',
    high: 'उच्च',
    engagement: 'एंगेजमेंट',
    videos: 'वीडियो',
    with: 'के साथ',
    ai: 'एआई',
    stop: 'रुकिए',
    scrolling: 'स्क्रॉल करना बंद करें',
    this: 'यह',
    changes: 'बदल देता है',
    everything: 'सब कुछ',
    the: 'यह',
    secret: 'रहस्य',
    growth: 'विकास',
    money: 'कमाई',
    how: 'कैसे',
    to: '',
    automate: 'स्वचालित करें',
    editing: 'संपादन',
    listen: 'ध्यान से',
    carefully: 'सुनें',
  },
  ja: {
    transform: '変革する',
    your: 'あなたの',
    content: 'コンテンツを',
    into: 'へ',
    viral: 'バイラルな',
    high: '高エンゲージメント',
    engagement: '反応',
    videos: '動画',
    with: 'AIで',
    ai: 'AI',
    stop: 'スクロールを',
    scrolling: '止めてください',
    this: 'これが',
    changes: 'すべてを変える',
    everything: 'すべてを',
    the: '',
    secret: '秘密',
    growth: '成長',
    money: '収益',
    how: '方法',
    to: 'の',
    automate: '自動化する',
    editing: '動画編集',
    listen: 'よく',
    carefully: '聞いてください',
  },
  pt: {
    transform: 'transforme',
    your: 'seu',
    content: 'conteúdo',
    into: 'em',
    viral: 'viral',
    high: 'alto',
    engagement: 'engajamento',
    videos: 'vídeos',
    with: 'com',
    ai: 'IA',
    stop: 'pare',
    scrolling: 'de rolar',
    this: 'isso',
    changes: 'muda',
    everything: 'tudo',
    the: 'o',
    secret: 'segredo',
    growth: 'crescimento',
    money: 'dinheiro',
    how: 'como',
    to: 'para',
    automate: 'automatizar',
    editing: 'edição',
    listen: 'ouça',
    carefully: 'com atenção',
  },
  it: {
    transform: 'trasforma',
    your: 'il tuo',
    content: 'contenuto',
    into: 'in',
    viral: 'virale',
    high: 'alto',
    engagement: 'coinvolgimento',
    videos: 'video',
    with: 'con',
    ai: 'IA',
    stop: 'fermati',
    scrolling: 'non scorrere',
    this: 'questo',
    changes: 'cambia',
    everything: 'tutto',
    the: 'il',
    secret: 'segreto',
    growth: 'crescita',
    money: 'denaro',
    how: 'come',
    to: 'per',
    automate: 'automatizzare',
    editing: 'editing',
    listen: 'ascolta',
    carefully: 'attentamente',
  },
  ar: {
    transform: 'حوّل',
    your: 'محتواك',
    content: 'المحتوى',
    into: 'إلى',
    viral: 'واسع الانتشار',
    high: 'عالي',
    engagement: 'التفاعل',
    videos: 'فيديوهات',
    with: 'باستخدام',
    ai: 'الذكاء الاصطناعي',
    stop: 'توقف عن',
    scrolling: 'التمرير',
    this: 'هذا',
    changes: 'يغير',
    everything: 'كل شيء',
    the: 'الـ',
    secret: 'السر',
    growth: 'النمو',
    money: 'الأرباح',
    how: 'كيف',
    to: 'لـ',
    automate: 'أتمتة',
    editing: 'المونتاج',
    listen: 'استمع',
    carefully: 'بعناية',
  },
  ko: {
    transform: '변환하세요',
    your: '당신의',
    content: '콘텐츠를',
    into: '로',
    viral: '바이럴',
    high: '높은',
    engagement: '참여도',
    videos: '영상',
    with: 'AI로',
    ai: 'AI',
    stop: '스크롤을',
    scrolling: '멈추세요',
    this: '이것이',
    changes: '모든 것을 바꿉니다',
    everything: '모든 것을',
    the: '',
    secret: '비밀',
    growth: '성장',
    money: '수익',
    how: '방법',
    to: '',
    automate: '자동화하는',
    editing: '영상 편집',
    listen: '집중해서',
    carefully: '들어보세요',
  },
  zh: {
    transform: '转变',
    your: '你的',
    content: '内容',
    into: '成为',
    viral: '爆款',
    high: '高互动',
    engagement: '互动率',
    videos: '视频',
    with: '借助',
    ai: 'AI',
    stop: '停下',
    scrolling: '滑动',
    this: '这',
    changes: '改变',
    everything: '一切',
    the: '',
    secret: '秘诀',
    growth: '增长',
    money: '变现',
    how: '如何',
    to: '',
    automate: '自动化',
    editing: '视频剪辑',
    listen: '仔细',
    carefully: '聆听',
  },
  ru: {
    transform: 'превратите',
    your: 'ваш',
    content: 'контент',
    into: 'в',
    viral: 'вирусные',
    high: 'высокое',
    engagement: 'вовлечение',
    videos: 'видео',
    with: 'с помощью',
    ai: 'ИИ',
    stop: 'перестаньте',
    scrolling: 'листать ленту',
    this: 'это',
    changes: 'меняет',
    everything: 'всё',
    the: '',
    secret: 'секрет',
    growth: 'рост',
    money: 'доход',
    how: 'как',
    to: '',
    automate: 'автоматизировать',
    editing: 'монтаж',
    listen: 'слушайте',
    carefully: 'внимательно',
  },
  nl: {
    transform: 'transformeer',
    your: 'jouw',
    content: 'content',
    into: 'in',
    viral: 'virale',
    high: 'hoge',
    engagement: 'betrokkenheid',
    videos: 'video\'s',
    with: 'met',
    ai: 'AI',
    stop: 'stop',
    scrolling: 'met scrollen',
    this: 'dit',
    changes: 'verandert',
    everything: 'alles',
    the: 'het',
    secret: 'geheim',
    growth: 'groei',
    money: 'geld',
    how: 'hoe',
    to: 'om te',
    automate: 'automatiseren',
    editing: 'bewerken',
    listen: 'luister',
    carefully: 'aandachtig',
  },
};

/**
 * Translates English text into a target language using structured dictionaries
 * with intelligent fallback for unmatched vocabulary.
 */
export function translateTranscript(
  text: string,
  targetLangCode: string
): string {
  if (!text || targetLangCode === 'en') return text;

  const dict = DICTIONARY[targetLangCode];
  if (!dict) return text;

  const words = text.split(/(\s+|[.,!?;:])/);
  const translated = words.map((chunk) => {
    const clean = chunk.toLowerCase().trim();
    if (!clean) return chunk;
    if (dict[clean]) {
      // Preserve first character capitalization if present
      const firstChar = chunk[0];
      const match = dict[clean];
      if (firstChar === firstChar.toUpperCase()) {
        return match.charAt(0).toUpperCase() + match.slice(1);
      }
      return match;
    }
    return chunk;
  });

  return translated.join('');
}
